/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.zerolcamb.formas;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JCheckBox;
import uam.zerolcamb.operaciones.OperacionesCheckBox;

/**
 *
 * @author Zerol
 */
public class FrmCheckBoxes extends javax.swing.JFrame {
    ArrayList<JCheckBox> listaArrayLenguajes = new ArrayList<>();
    LinkedList<JCheckBox> listaLinkedLenguajes = new LinkedList<>();
    /**
     * Creates new form FrmCheckBoxes
     */
    public FrmCheckBoxes() {
        initComponents();
        llenarCheckBoxesLinked();
        llenarCheckboxesArray();
        txtOtroLenguaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLenguajes = new javax.swing.JLabel();
        lblIdiomas = new javax.swing.JLabel();
        cbC = new javax.swing.JCheckBox();
        cbCpp = new javax.swing.JCheckBox();
        cbJava = new javax.swing.JCheckBox();
        cbOtro = new javax.swing.JCheckBox();
        cbIngles = new javax.swing.JCheckBox();
        cbFrances = new javax.swing.JCheckBox();
        cbAleman = new javax.swing.JCheckBox();
        lblPreferencias = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtOtroLenguaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLenguajes.setText("Lenguajes");

        lblIdiomas.setText("Idiomas");

        cbC.setText("C");

        cbCpp.setText("C++");

        cbJava.setText("Java");

        cbOtro.setText("Otro");
        cbOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOtroActionPerformed(evt);
            }
        });

        cbIngles.setText("Inglés");

        cbFrances.setText("Francés");

        cbAleman.setText("Alemán");

        lblPreferencias.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPreferencias.setText("Preferencias de cursos");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLenguajes)
                                    .addComponent(cbC)
                                    .addComponent(cbCpp)
                                    .addComponent(cbJava))
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAleman)
                                    .addComponent(cbFrances)
                                    .addComponent(cbIngles)
                                    .addComponent(lblIdiomas)))
                            .addComponent(lblPreferencias)
                            .addComponent(txtOtroLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbOtro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPreferencias)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLenguajes)
                    .addComponent(lblIdiomas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbC)
                    .addComponent(cbIngles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCpp)
                    .addComponent(cbFrances))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJava)
                    .addComponent(cbAleman))
                .addGap(18, 18, 18)
                .addComponent(cbOtro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOtroLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        OperacionesCheckBox operacionesCheckBox = new OperacionesCheckBox();
        operacionesCheckBox.obtenerCursosLenguajes(listaArrayLenguajes);
        if(cbOtro.isSelected()) System.out.println(txtOtroLenguaje.getText());
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOtroActionPerformed
        txtOtroLenguaje.setText("");
        txtOtroLenguaje.setVisible(cbOtro.isSelected());
        setVisible(true);
    }//GEN-LAST:event_cbOtroActionPerformed

    /**
     * @param args the command line arguments
     */
    private void llenarCheckboxesArray(){
        listaArrayLenguajes.add(cbC);
        listaArrayLenguajes.add(cbCpp);
        listaArrayLenguajes.add(cbJava);
        listaArrayLenguajes.add(cbOtro);
    }
    
    private void llenarCheckBoxesLinked(){
        listaLinkedLenguajes.add(cbC);
        listaLinkedLenguajes.add(cbCpp);
        listaLinkedLenguajes.add(cbJava);
        listaLinkedLenguajes.add(cbOtro);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCheckBoxes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCheckBoxes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cbAleman;
    private javax.swing.JCheckBox cbC;
    private javax.swing.JCheckBox cbCpp;
    private javax.swing.JCheckBox cbFrances;
    private javax.swing.JCheckBox cbIngles;
    private javax.swing.JCheckBox cbJava;
    private javax.swing.JCheckBox cbOtro;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblLenguajes;
    private javax.swing.JLabel lblPreferencias;
    private javax.swing.JTextField txtOtroLenguaje;
    // End of variables declaration//GEN-END:variables
}
