/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.zerolcamb.formas;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author Zerol
 */
public class FrmRadioButtons extends javax.swing.JFrame {

    /**
     * Creates new form FrmRadioButtons
     */
    public FrmRadioButtons() {
        initComponents();
        asignarRadioButtons();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgroupEstadoCivil = new javax.swing.ButtonGroup();
        lblEncuesta = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblNacionalidad = new javax.swing.JLabel();
        rbCasado = new javax.swing.JRadioButton();
        rbSoltero = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbUnionLibre = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        rbMexicana = new javax.swing.JRadioButton();
        rbExtranjera = new javax.swing.JRadioButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEncuesta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEncuesta.setText("Encuesta");

        lblEstadoCivil.setText("Estado civil");

        lblGenero.setText("Género");

        lblNacionalidad.setText("Nacionalidad");

        rbCasado.setText("Casado");

        rbSoltero.setText("Soltero");

        rbDivorciado.setText("DSS");

        rbUnionLibre.setText("Unión libre");

        rbHombre.setText("Hombre");

        rbMujer.setText("Mujer");

        rbMexicana.setText("Mexicana");

        rbExtranjera.setText("Extranjera");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMexicana)
                        .addGap(18, 18, 18)
                        .addComponent(rbExtranjera))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbHombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbMujer))
                    .addComponent(lblEncuesta)
                    .addComponent(lblEstadoCivil)
                    .addComponent(lblGenero)
                    .addComponent(lblNacionalidad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCasado)
                        .addGap(18, 18, 18)
                        .addComponent(rbSoltero)
                        .addGap(18, 18, 18)
                        .addComponent(rbDivorciado)
                        .addGap(18, 18, 18)
                        .addComponent(rbUnionLibre)))
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblEncuesta)
                .addGap(34, 34, 34)
                .addComponent(lblEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCasado)
                    .addComponent(rbSoltero)
                    .addComponent(rbDivorciado)
                    .addComponent(rbUnionLibre))
                .addGap(24, 24, 24)
                .addComponent(lblGenero)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer))
                .addGap(18, 18, 18)
                .addComponent(lblNacionalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMexicana)
                    .addComponent(rbExtranjera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String resultado = seleccionarEstadoCivil();
        System.out.println(resultado);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void asignarRadioButtons(){
        bgroupEstadoCivil.add(rbCasado);
        bgroupEstadoCivil.add(rbDivorciado);
        bgroupEstadoCivil.add(rbSoltero);
        bgroupEstadoCivil.add(rbUnionLibre);
        rbCasado.setSelected(true);
    }
 
    private String seleccionarEstadoCivil(){
        Enumeration<AbstractButton> btnGrp = bgroupEstadoCivil.getElements();
        String resultado = "";
        
        while (btnGrp.hasMoreElements()) {
            JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
            if(btnAux.isSelected()){
                resultado = btnAux.getText();
                break;
            }
        }
        return resultado;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRadioButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRadioButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRadioButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRadioButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRadioButtons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgroupEstadoCivil;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblEncuesta;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbExtranjera;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMexicana;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbSoltero;
    private javax.swing.JRadioButton rbUnionLibre;
    // End of variables declaration//GEN-END:variables
}
