/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.zerolcamb.formas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uam.zerolcamb.clases.Alumno;
import uam.zerolcamb.operaciones.OperacionesAlumnos;

/**
 *
 * @author Zerol
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /* Nuestra base de datos sera un ArrayList global */
    ArrayList<Alumno> baseDeDatos;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        iniciarBaseDeDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBoleta = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtBoleta = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Inicio de Sesión");

        lblBoleta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBoleta.setText("Boleta");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPassword.setText("Contraseña");

        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        menuAcercaDe.setText("Acerca De");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(menuAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btnIniciar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addComponent(btnRegistrarse))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBoleta)
                                .addComponent(lblPassword))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBoleta)
                                .addComponent(pwdPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoleta)
                    .addComponent(txtBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnRegistrarse))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        /* Si en el menú superior se selecciona la opción de salir, se termina el programa */
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
       /* Si en el menú superior se selecciona la opción de acercaDe
          se abre una ventana con un mensaje utilizando la clase JOptionPane
          y su metodo showMessageDialog
        */
       /* Con 4 parametros */
       
       JOptionPane.showMessageDialog(this, "Programa realizado por Zerol", "Acerca de", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        /* Si se da click en registrarse entonces se movera a la pantalla de registro */
        FrmRegistrarse fr = new FrmRegistrarse(baseDeDatos);
        fr.setVisible(true);
        /* Se cierra esta pantalla */
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        /* Se intentara iniciar sesión */
        OperacionesAlumnos operacionesAlumnos = new OperacionesAlumnos();
        /* Se buscara un alumno en la base de datos a partir de lo escrito en el
           textfield de boleta
        */
        Alumno alumno = operacionesAlumnos.buscarAlumno(baseDeDatos, txtBoleta.getText());
        /* Si no existe */
        if(alumno == null){
            /* Saldra un mensaje de error de que no existe ese alumno */
            JOptionPane.showMessageDialog(this, "No se encontro el alumno", "ERROR", JOptionPane.ERROR_MESSAGE);
        /* Sí si existe y la contraseña es igual a la del alumno con esa boleta */
        }else if(alumno.getContraseña().equals(new String(pwdPassword.getPassword()))){
            /* Se imprimira un mensaje de bienvenida */
            JOptionPane.showMessageDialog(this, "Bienvenido :)", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            /* Se inicializará la ventana de Visualizar alumno construyendolo
               y enviandole el alumno que inicio sesion
            */
            FrmVisualizarAlumno fva = new FrmVisualizarAlumno(alumno);
            fva.setVisible(true);
            /* Se cierra esta ventana */
            this.dispose();
        }else{
            /* Si la contraseña no es correcta, se imprimira una ventana de error */
            JOptionPane.showMessageDialog(this, "La contraseña no es correcta", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void iniciarBaseDeDatos(){
        /* Se inicializara nuestra base de datos desde un archivo */
        OperacionesAlumnos oa = new OperacionesAlumnos();
        try {
            /* con el método leeArchivo de la clase OperacionesAlumnos
               recuperamos la base de datos
            */
            baseDeDatos = oa.leeArchivo();
        } catch (IOException ex) {
            /* Si no existe el archivo, esto esta bien pues trabajaremos con una
               base de datos "vacia", continuaremos el programa inicializando
               nuestra lista baseDeDatos, si todo es correcto al registrar un
               alumno nuevo crearemos un archivo con esta lista la cual
               podremos recuperar despues
            */
            System.out.println("Se creo la base de datos");
            baseDeDatos = new ArrayList<>();
        } catch (ClassNotFoundException ex) {
            /* Si hubo un error al convertir el objeto dentro del archivo,
               se cerrara el programa.
            */
            JOptionPane.showMessageDialog(this, "Hubo un error al leer el archivo", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBoleta;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtBoleta;
    // End of variables declaration//GEN-END:variables
}
